# Generated by Django 4.0.1 on 2022-10-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('i_20_upload', '0002_i_20_upload_checked_by_i_20_upload_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicali_20_upload',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='i_20_upload',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
