# Generated by Django 4.1.3 on 2022-11-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_visa_interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmockvisainterviewanswer',
            name='final',
        ),
        migrations.RemoveField(
            model_name='mockvisainterviewanswer',
            name='final',
        ),
        migrations.AddField(
            model_name='historicalmockvisainterviewsession',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mockvisainterviewsession',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
