# Generated by Django 4.0.1 on 2022-11-04 05:13

import apps.mock_visa_interview.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_visa_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmockvisainterviewquestion',
            name='question_audio',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Question Audio'),
        ),
        migrations.AddField(
            model_name='mockvisainterviewquestion',
            name='question_audio',
            field=models.FileField(blank=True, null=True, upload_to=apps.mock_visa_interview.models.upload_to_path_question, verbose_name='Question Audio'),
        ),
    ]
