# Generated by Django 4.1.3 on 2022-11-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_visa_interview', '0002_historicalmockvisainterviewquestion_question_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmockvisainterviewanswer',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mockvisainterviewanswer',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
