# Generated by Django 4.0.1 on 2022-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='isNewApplicant',
            field=models.BooleanField(default=True),
        ),
    ]
