# Generated by Django 4.0.1 on 2022-09-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_isevaluated_profile_isnewapplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
    ]
