# Generated by Django 4.0.1 on 2022-09-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isEvaluated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='isNewApplicant',
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplicationstatus',
            name='isEvaluated',
            field=models.BooleanField(default=False),
        ),
    ]
