# Generated by Django 4.0.1 on 2022-09-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_isevaluated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='historicalapplicationstatus',
            name='orientation',
        ),
    ]
