# Generated by Django 4.0.1 on 2022-10-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_applicationstatus_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='application_submission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=0, verbose_name='Application Submission'),
        ),
        migrations.AddField(
            model_name='historicalapplicationstatus',
            name='application_submission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=0, verbose_name='Application Submission'),
        ),
    ]
