# Generated by Django 4.0.1 on 2022-10-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_applicationstatus_application_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='documents_upload',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=1, verbose_name='Documents Upload'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='file_opening',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=1, verbose_name='File Opening'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='pre_application_form',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=1, verbose_name='Pre-Application Form'),
        ),
        migrations.AlterField(
            model_name='historicalapplicationstatus',
            name='documents_upload',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=1, verbose_name='Documents Upload'),
        ),
        migrations.AlterField(
            model_name='historicalapplicationstatus',
            name='file_opening',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=1, verbose_name='File Opening'),
        ),
        migrations.AlterField(
            model_name='historicalapplicationstatus',
            name='pre_application_form',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Complete')], default=1, verbose_name='Pre-Application Form'),
        ),
    ]
