# Generated by Django 4.0.1 on 2022-09-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='middle_initials',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='middle_initials',
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name'),
        ),
    ]
