# Generated by Django 4.1.3 on 2022-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='dependents',
            field=models.JSONField(blank=True, null=True, verbose_name='Dependents'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='desired_field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desired Field of Study'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='desired_level_of_study',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desired Level of Study'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='eca_activities',
            field=models.JSONField(blank=True, null=True, verbose_name='Extracurricular Activities'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='eca_specific_achievements',
            field=models.JSONField(blank=True, null=True, verbose_name='Specific Extracurricular Achievements'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='grade_10th_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Grade 10th Subjects'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='grade_12th_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Grade 12th Subjects'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='graduate_degree_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Graduate Degree Subjects'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='parents',
            field=models.JSONField(blank=True, null=True, verbose_name='Parents'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='total_number_of_visa_needed',
            field=models.CharField(default=1, max_length=5, verbose_name='Total Number of Visa Needed'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='undergraduate_degree_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Undergraduate Degree Subjects'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='dependents',
            field=models.JSONField(blank=True, null=True, verbose_name='Dependents'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='desired_field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desired Field of Study'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='desired_level_of_study',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desired Level of Study'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='eca_activities',
            field=models.JSONField(blank=True, null=True, verbose_name='Extracurricular Activities'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='eca_specific_achievements',
            field=models.JSONField(blank=True, null=True, verbose_name='Specific Extracurricular Achievements'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='grade_10th_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Grade 10th Subjects'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='grade_12th_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Grade 12th Subjects'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='graduate_degree_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Graduate Degree Subjects'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='parents',
            field=models.JSONField(blank=True, null=True, verbose_name='Parents'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='total_number_of_visa_needed',
            field=models.CharField(default=1, max_length=5, verbose_name='Total Number of Visa Needed'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='undergraduate_degree_subjects',
            field=models.JSONField(blank=True, null=True, verbose_name='Undergraduate Degree Subjects'),
        ),
    ]
