# Generated by Django 4.0.1 on 2022-09-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application_form', '0002_remove_historicalpreapplicationform_middle_initials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='duolingo_score',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_score',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_score',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='duolingo_score',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_score',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_score',
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Proficiency Score'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Proficiency Score'),
        ),
    ]
