# Generated by Django 4.0.1 on 2022-09-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_application_form', '0002_remove_historicalpreapplicationform_middle_initials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='duolingo_date_of_examination',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='duolingo_score',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_date_of_examination',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_listening',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_reading',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_score',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_speaking',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_trf_no',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_waivers',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='ielts_writing',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_date_of_examination',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_listening',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_reading',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_score',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_speaking',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_trf_no',
        ),
        migrations.RemoveField(
            model_name='historicalpreapplicationform',
            name='toefl_writing',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='duolingo_date_of_examination',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='duolingo_score',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_date_of_examination',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_listening',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_reading',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_score',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_speaking',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_trf_no',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_waivers',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='ielts_writing',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_date_of_examination',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_listening',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_reading',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_score',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_speaking',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_trf_no',
        ),
        migrations.RemoveField(
            model_name='preapplicationform',
            name='toefl_writing',
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_date_of_examination',
            field=models.DateField(blank=True, null=True, verbose_name='English Proficiency Test Date'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_listening',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Listening'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_reading',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Reading'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Proficiency Score'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_speaking',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Speaking'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_trf_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Proficiency TRF No.'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_waivers',
            field=models.BooleanField(default=False, verbose_name='English Proficiency Waiver?'),
        ),
        migrations.AddField(
            model_name='historicalpreapplicationform',
            name='english_proficiency_writing',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Writing'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_date_of_examination',
            field=models.DateField(blank=True, null=True, verbose_name='English Proficiency Test Date'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_listening',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Listening'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_reading',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Reading'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_score',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Proficiency Score'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_speaking',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Speaking'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_trf_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='English Proficiency TRF No.'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_waivers',
            field=models.BooleanField(default=False, verbose_name='English Proficiency Waiver?'),
        ),
        migrations.AddField(
            model_name='preapplicationform',
            name='english_proficiency_writing',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='English Proficiency Writing'),
        ),
    ]
