# Generated by Django 4.0.1 on 2022-09-28 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
